# Generated by Django 3.2 on 2023-11-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CVEapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clients_count', models.IntegerField(default=0)),
                ('invoices_count', models.IntegerField(default=0)),
                ('contracts_count', models.IntegerField(default=0)),
                ('staff_count', models.IntegerField(default=0)),
            ],
        ),
    ]
